#!/ur/bin/env python
from __future__ import print_function, division
from astropy.io import fits
from argparse import ArgumentParser

def main(args):
    uvfits = fits.open(args.uvfits)
    ra = uvfits[0].header["CRVAL5"]
    dec = uvfits[0].header['CRVAL6']
    date_obs = uvfits[0].header['DATE-OBS']
    
    ## create new metafits file
    new_header = fits.Header({"RA" : ra, "DEC" : dec, "DATE-OBS" : date_obs, "COMMENT" : "metafits generated by steve, as it is required by the shift-stack pipeline"})
    hdu = fits.PrimaryHDU(header=new_header)
    hdul = fits.HDUList([hdu])
    hdul.writeto('{}.metafits'.format(args.obs))







if __name__ == "__main__":
    parser = ArgumentParser("makeMetaFits", description="creates metafits file from uvfits file")
    parser.add_argument("--uvfits", required=True, help="the uvfits file for the observation")
    parser.add_argument("--exposure", default=120, type=int, help="the exposure of the observation")
    parser.add_argument("--obs", required=True, type=int, help="the obs id of the observation")
    args = parser.parse_args()

    main(args)

